import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import TanstackProvider from "@/provider/Tanstack-provider";
import Provider from "@/provider/authprovider";
import { CartProvider } from "@/provider/cart-provider";

import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/Footer";
// import { SessionProvider } from "next-auth/react";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Game creater App",
  description: "Generated by create Ammir_Immani Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        <TanstackProvider>
          <Provider>
            <CartProvider>
              <div className=" h-screen flex flex-col justify-between">
                <Navbar />
                {children}
                <Footer />
              </div>
            </CartProvider>
          </Provider>
        </TanstackProvider>
      </body>
    </html>
  );
}
